services:

  eureka-server:
    build:
      context: ./eureka
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - hospital-net

  user-service:
    build:
      context: ./user
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - hospital-net

networks:
  hospital-net:
    driver: bridge
