services:

  eureka-server:
    build:
      context: ./Backend/Eureka/Eureka
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - hospital-net

  user-service:
    build:
      context: ./Backend/Services/User
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - hospital-net

  auth-service:
    build:
      context: ./Backend/Services/Auth
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    networks:
      - hospital-net

  admin-service:
    build:
      context: ./Backend/Services/Admin
    container_name: admin-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    networks:
      - hospital-net

  doctor-service:
    build:
      context: ./Backend/Services/Doctor
    container_name: doctor-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    networks:
      - hospital-net

  diagnosis-service:
    build:
      context: ./Backend/Services/Diagnosis
    container_name: diagnosis-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
    networks:
      - hospital-net

  chat-service:
    build:
      context: ./Backend/Services/Chat
    container_name: chat-service
    ports:
      - "8087:8087"
    depends_on:
      - eureka-server
    networks:
      - hospital-net

  appointment-service:
    build:
      context: ./Backend/Services/Appointment
    container_name: appointment-service
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server
    networks:
      - hospital-net

  gateway-service:
    build:
      context: ./Backend/Gateway/Spring-Cloud-Gateway
    container_name: spring-cloud-gateway-service
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
    networks:
      - hospital-net

networks:
  hospital-net:
    driver: bridge
